### ISSUE TITLE
f2e-server升级了吗？我一脸慒逼。

### ISSUE THREAD

**Issue by qzmly100** [shy2850/f2e-server#2]
原来的方法是cd node_modules && f2e-server 
npm start 打开网页就能直接修改静态文件目录。
现在用新版本了。我几乎看不懂怎么启动静态文件啊。
看了f2econfig.js  文件。实在没明白。
是和koa 和express一起使用吗？
过去不是这样的，为什么会改版？

**Comment by shy2850** [comment]
1. 你可以通过 增加安装版本号继续使用 f2e-server v1.*的版本   `npm i f2e-server@1.*`
2. 在新版中 全局安装完成后， 在任意目录 使用命令 `f2e start` 就可以启动为静态服务器，并打开浏览器。
3. f2e-server 2.0 版本主要考虑到 更多和构建输出相关的东西， 想通过兼容请求流和文件系统构建流，让它既作为资源服务器，还能提供基本的构建流程配置， 所有相关的配置接口都在 `.f2econfig.js` 中摆出来，使用时候不需要的可以删除。   1.*版本的时候所有事情都在请求中处理的，启动速度虽然很快，运行时重复编译的内容过多。

4. 新版配置接口描述： [https://f2e-server.com/zhong-jian-jian-kai-fa.html](https://f2e-server.com/zhong-jian-jian-kai-fa.html)

5. 对于 koa 和 express的支持 主要考虑到它们启动 https 服务，以及域名配置什么的， 这里也可以作为小工具帮忙完成。

**Comment by shy2850** [comment]
接下来， 新版主要考虑新增 代理相关的中间件、 以及支持部分 webpack-loader

**Comment by qzmly100** [comment]
非常感谢！

**Comment by shy2850** [comment]
你可以加入 QQ群： 208919902。 在这里面我会更快看到和回复
